name: ViaggioTreno
options: # Some general settings for the project
    bundleIdPrefix: com.viaggiotreno
    createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
    indentWidth: 2 # indent by 2 spaces
    tabWidth: 2 # a tab is 2 spaces
settings:
    DEVELOPMENT_TEAM: None
targets:
  ViaggioTreno:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: ViaggioTreno
    dependencies:
        - target: Features
        - target: Styling
  Features: # Feature
    type: framework
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: Features
    dependencies:
        - target: Styling
  Styling: # Common
    type: framework
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: AppTheme/Styling
  ViaggioTrenoTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: ViaggioTrenoTests
    dependencies:
        - target: ViaggioTreno
