name: pendolarestanco
options: # Some general settings for the project
    bundleIdPrefix: com.bordet
    createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
    indentWidth: 4
    tabWidth: 4
settings:
    DEVELOPMENT_TEAM: None
targets:
  PendolareStanco:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: ViaggioTreno
    dependencies:
        - target: Styling
        - target: Networking
        - target: FileClient
  Styling: # Common
    type: framework
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: AppTheme/Styling
  Networking:
    type: framework
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: Networking
  FileClient:
    type: framework
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: FileClient
    dependencies:
        - target: Networking
  PendolareStancoTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: ViaggioTrenoTests
    dependencies:
        - target: PendolareStanco
