# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

source 'https://github.com/jrBordet/Sources.git'
source 'https://cdn.cocoapods.org/'

def caprice
  pod 'Caprice', '0.0.5' #:path => '../../Caprice'
end

target 'FileClientDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlarmsDemo
  pod 'SceneBuilder', '1.0.0'

  pod 'RxComposableArchitecture', '1.0.0' # :path => '../../RxComposableArchitecture'

  target 'FileClientDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapshotTesting', '~> 1.7.2'
    pod 'RxComposableArchitectureTests', :path => '../../RxComposableArchitecture'#'1.0.0'
    caprice
  end

end

target 'FileClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlarmsDemo
  pod 'SceneBuilder', '1.0.0'
  pod 'RxComposableArchitecture', '1.0.0' # :path => '../../RxComposableArchitecture'
  pod 'RxDataSources', '4.0.1'

  # Local pods
  pod 'Styling', :path => '../AppTheme'
  caprice
  
end
