name: FileClientDemo
options: # Some general settings for the project
    bundleIdPrefix: com.fileclientdemo
    createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
    #indentWidth: 2 # indent by 2 spaces
    #tabWidth: 2 # a tab is 2 spaces
settings:
    DEVELOPMENT_TEAM: None
targets:
  FileClientDemo:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: FileClientDemo
    dependencies:
        - target: FileClient
  FileClientDemoTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: FileClientDemoTests
    dependencies:
        - target: FileClientDemo
  FileClient: # Feature
    type: framework
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: FileClient
