name: NetworkingDemo
options: # Some general settings for the project
    bundleIdPrefix: com.networking
    createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
#    indentWidth: 2 # indent by 2 spaces
#    tabWidth: 2 # a tab is 2 spaces
settings:
    DEVELOPMENT_TEAM: None
targets:
  NetworkingDemo:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: NetworkingDemo
    dependencies:
        - target: Networking
  NetworkingDemoTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: NetworkingDemoTests
    dependencies:
        - target: NetworkingDemo
  # Styling pod library
  Networking:
    type: framework
    platform: iOS
    deploymentTarget: 10.0
    sources:
        - path: Networking
