# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/jrBordet/Sources.git'
source "https://cdn.cocoapods.org/"

def caprice
  pod 'Caprice', '0.0.5' #:path => '../../Caprice'
end
 
target 'AppTheme' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppTheme
  pod 'SceneBuilder', '1.0.0'
  pod 'SwiftGen', '~> 6.0'
  caprice

  target 'AppThemeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapshotTesting', '~> 1.7.2'
  end

end

target 'Styling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppTheme
  caprice

end
